modLoader="javafml"
loaderVersion="[31.1,)"
license="MIT"

[[mods]]
modId="integratednbt"
version="1.6.0"
displayName="Integrated NBT"
authors="Rin Tepis"
description='''
Integrated NBT is an addon for Integrated Dynamics. It offers a simpler way of extracting deeply nested NBT values.
'''
[[dependencies.integratednbt]]
    modId="integrateddynamics"
    mandatory=true
    versionRange="[1.11.9,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.integratednbt]]
    modId="forge"
    mandatory=true
    versionRange="[43.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratednbt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
